Widget component
Shemchuk/travel-app pull request #16
Opened 2021-03-17 19:23 UTC by durden666

2021-03-17 19:27 UTC, Shemchuk approved these changes

2021-03-17 19:37 UTC, Andrew-6676 requested changes

2021-03-17 19:37 UTC, Andrew-6676 commented on src/components/countryPageComponents/Clock.tsx
> +  const { timezone } = country;
There is no `timezone` in the Country model (and in the backend data too)

2021-03-17 19:52 UTC, Shemchuk requested changes
- Need to add timezone field to the interface ICountry
- Should be added timezone to file "countries-data"

2021-03-17 20:28 UTC, seha1 approved these changes

2021-03-17 20:28 UTC, seha1 approved these changes

2021-03-17 20:31 UTC, Andrew-6676 approved these changes

2021-03-17 21:36 UTC, seha1 approved these changes

2021-03-17 21:37 UTC, seha1 approved these changes

2021-03-18 03:00 UTC, Shemchuk approved these changes

2021-03-18 03:02 UTC, merged